version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: todo-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_DB: todo_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: todo-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DB_HOST: todo-postgres
      DB_USER: todo_user
      DB_PASSWORD: todo_pass
      DB_NAME: todo_db

volumes:
  pgdata:
